function Action(S, action)

% ACTION - Take an action for a sheetlet
%
%   Action(S, action)
%
%   Take an action for the sheetlet.  Action is a string that is either
%   generated by a program.  When a user clicks on a uicontrol, the Action string
%   corresponds to the last word of the 'Tag' of the control.


disp(['sheetlet ' NameString(S) ' of class ' class(S) ' requested action ' action '.']);
